// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_search.proto

// Protobuf Java Version: 3.25.5
package com.plato.search;

public interface SearchResultItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.SearchResultItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1. 定位核心信息 (用于点击后跳转到 Timeline)
   * </pre>
   *
   * <code>uint64 msg_id = 1;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>uint64 session_id = 2;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <pre>
   * 关键：前端拿到这个 ID，调用 GetMessages(anchor=seq_id) 拉取前后文
   * </pre>
   *
   * <code>uint64 seq_id = 3;</code>
   * @return The seqId.
   */
  long getSeqId();

  /**
   * <pre>
   * 2. 展示信息
   * </pre>
   *
   * <code>uint64 sender_id = 4;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <code>int64 create_time_ms = 5;</code>
   * @return The createTimeMs.
   */
  long getCreateTimeMs();

  /**
   * <pre>
   * 3. 高亮片段 (Highlighting)
   * 重点：不要返回原始的 full content。
   * ES 会返回类似 "你好，这里是&lt;em&gt;项目&lt;/em&gt;..." 的片段。
   * 能够极大减少网络传输带宽。
   * </pre>
   *
   * <code>string highlight_content = 6;</code>
   * @return The highlightContent.
   */
  java.lang.String getHighlightContent();
  /**
   * <pre>
   * 3. 高亮片段 (Highlighting)
   * 重点：不要返回原始的 full content。
   * ES 会返回类似 "你好，这里是&lt;em&gt;项目&lt;/em&gt;..." 的片段。
   * 能够极大减少网络传输带宽。
   * </pre>
   *
   * <code>string highlight_content = 6;</code>
   * @return The bytes for highlightContent.
   */
  com.google.protobuf.ByteString
      getHighlightContentBytes();

  /**
   * <pre>
   * 4. 原始类型 (用于前端展示不同的图标，如 [文件]、[图片])
   * </pre>
   *
   * <code>int32 msg_type = 7;</code>
   * @return The msgType.
   */
  int getMsgType();
}
