// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_search.proto

// Protobuf Java Version: 3.25.5
package com.plato.search;

/**
 * <pre>
 * -------------------------------------------------------
 * Response Definitions
 * -------------------------------------------------------
 * </pre>
 *
 * Protobuf type {@code com.plato.gateway.SearchMessagesResponse}
 */
public final class SearchMessagesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.gateway.SearchMessagesResponse)
    SearchMessagesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchMessagesResponse.newBuilder() to construct.
  private SearchMessagesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchMessagesResponse() {
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SearchMessagesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.search.StorageSearch.internal_static_com_plato_gateway_SearchMessagesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.search.StorageSearch.internal_static_com_plato_gateway_SearchMessagesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.search.SearchMessagesResponse.class, com.plato.search.SearchMessagesResponse.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.plato.search.SearchResultItem> items_;
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.plato.search.SearchResultItem> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.plato.search.SearchResultItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  @java.lang.Override
  public com.plato.search.SearchResultItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  @java.lang.Override
  public com.plato.search.SearchResultItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int TOTAL_HITS_FIELD_NUMBER = 2;
  private long totalHits_ = 0L;
  /**
   * <pre>
   * 总命中数 (用于 UI 显示 "找到 500+ 条相关记录")
   * </pre>
   *
   * <code>int64 total_hits = 2;</code>
   * @return The totalHits.
   */
  @java.lang.Override
  public long getTotalHits() {
    return totalHits_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (totalHits_ != 0L) {
      output.writeInt64(2, totalHits_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (totalHits_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalHits_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.search.SearchMessagesResponse)) {
      return super.equals(obj);
    }
    com.plato.search.SearchMessagesResponse other = (com.plato.search.SearchMessagesResponse) obj;

    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (getTotalHits()
        != other.getTotalHits()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_HITS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalHits());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.search.SearchMessagesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.search.SearchMessagesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.search.SearchMessagesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.search.SearchMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.search.SearchMessagesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * -------------------------------------------------------
   * Response Definitions
   * -------------------------------------------------------
   * </pre>
   *
   * Protobuf type {@code com.plato.gateway.SearchMessagesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.gateway.SearchMessagesResponse)
      com.plato.search.SearchMessagesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.search.StorageSearch.internal_static_com_plato_gateway_SearchMessagesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.search.StorageSearch.internal_static_com_plato_gateway_SearchMessagesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.search.SearchMessagesResponse.class, com.plato.search.SearchMessagesResponse.Builder.class);
    }

    // Construct using com.plato.search.SearchMessagesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalHits_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.search.StorageSearch.internal_static_com_plato_gateway_SearchMessagesResponse_descriptor;
    }

    @java.lang.Override
    public com.plato.search.SearchMessagesResponse getDefaultInstanceForType() {
      return com.plato.search.SearchMessagesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.search.SearchMessagesResponse build() {
      com.plato.search.SearchMessagesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.search.SearchMessagesResponse buildPartial() {
      com.plato.search.SearchMessagesResponse result = new com.plato.search.SearchMessagesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.plato.search.SearchMessagesResponse result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(com.plato.search.SearchMessagesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalHits_ = totalHits_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.search.SearchMessagesResponse) {
        return mergeFrom((com.plato.search.SearchMessagesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.search.SearchMessagesResponse other) {
      if (other == com.plato.search.SearchMessagesResponse.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.getTotalHits() != 0L) {
        setTotalHits(other.getTotalHits());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.plato.search.SearchResultItem m =
                  input.readMessage(
                      com.plato.search.SearchResultItem.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              totalHits_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.plato.search.SearchResultItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        items_ = new java.util.ArrayList<com.plato.search.SearchResultItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plato.search.SearchResultItem, com.plato.search.SearchResultItem.Builder, com.plato.search.SearchResultItemOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public java.util.List<com.plato.search.SearchResultItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public com.plato.search.SearchResultItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.plato.search.SearchResultItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder setItems(
        int index, com.plato.search.SearchResultItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder addItems(com.plato.search.SearchResultItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.plato.search.SearchResultItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder addItems(
        com.plato.search.SearchResultItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder addItems(
        int index, com.plato.search.SearchResultItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.plato.search.SearchResultItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public com.plato.search.SearchResultItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public com.plato.search.SearchResultItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public java.util.List<? extends com.plato.search.SearchResultItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public com.plato.search.SearchResultItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.plato.search.SearchResultItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public com.plato.search.SearchResultItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.plato.search.SearchResultItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 搜索结果列表
     * </pre>
     *
     * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
     */
    public java.util.List<com.plato.search.SearchResultItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plato.search.SearchResultItem, com.plato.search.SearchResultItem.Builder, com.plato.search.SearchResultItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.plato.search.SearchResultItem, com.plato.search.SearchResultItem.Builder, com.plato.search.SearchResultItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private long totalHits_ ;
    /**
     * <pre>
     * 总命中数 (用于 UI 显示 "找到 500+ 条相关记录")
     * </pre>
     *
     * <code>int64 total_hits = 2;</code>
     * @return The totalHits.
     */
    @java.lang.Override
    public long getTotalHits() {
      return totalHits_;
    }
    /**
     * <pre>
     * 总命中数 (用于 UI 显示 "找到 500+ 条相关记录")
     * </pre>
     *
     * <code>int64 total_hits = 2;</code>
     * @param value The totalHits to set.
     * @return This builder for chaining.
     */
    public Builder setTotalHits(long value) {

      totalHits_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总命中数 (用于 UI 显示 "找到 500+ 条相关记录")
     * </pre>
     *
     * <code>int64 total_hits = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalHits() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalHits_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.gateway.SearchMessagesResponse)
  }

  // @@protoc_insertion_point(class_scope:com.plato.gateway.SearchMessagesResponse)
  private static final com.plato.search.SearchMessagesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.search.SearchMessagesResponse();
  }

  public static com.plato.search.SearchMessagesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchMessagesResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchMessagesResponse>() {
    @java.lang.Override
    public SearchMessagesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SearchMessagesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchMessagesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.search.SearchMessagesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

