// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_search.proto

// Protobuf Java Version: 3.25.5
package com.plato.search;

public interface SearchMessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.SearchMessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  java.util.List<com.plato.search.SearchResultItem> 
      getItemsList();
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  com.plato.search.SearchResultItem getItems(int index);
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  java.util.List<? extends com.plato.search.SearchResultItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * 搜索结果列表
   * </pre>
   *
   * <code>repeated .com.plato.gateway.SearchResultItem items = 1;</code>
   */
  com.plato.search.SearchResultItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <pre>
   * 总命中数 (用于 UI 显示 "找到 500+ 条相关记录")
   * </pre>
   *
   * <code>int64 total_hits = 2;</code>
   * @return The totalHits.
   */
  long getTotalHits();
}
