// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_search.proto

// Protobuf Java Version: 3.25.5
package com.plato.search;

public final class StorageSearch {
  private StorageSearch() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SearchMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SearchMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SearchMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SearchMessagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SearchResultItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SearchResultItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024storage_search.proto\022\021com.plato.gatewa" +
      "y\"\326\001\n\025SearchMessagesRequest\022\017\n\007keyword\030\001" +
      " \001(\t\022\024\n\nsession_id\030\002 \001(\004H\000\022\022\n\010owner_id\030\003" +
      " \001(\004H\000\022\021\n\tmsg_types\030\004 \003(\005\022\025\n\rstart_time_" +
      "ms\030\005 \001(\003\022\023\n\013end_time_ms\030\006 \001(\003\022\022\n\nsender_" +
      "ids\030\007 \003(\004\022\023\n\013page_number\030\010 \001(\005\022\021\n\tpage_s" +
      "ize\030\t \001(\005B\007\n\005scope\"`\n\026SearchMessagesResp" +
      "onse\0222\n\005items\030\001 \003(\0132#.com.plato.gateway." +
      "SearchResultItem\022\022\n\ntotal_hits\030\002 \001(\003\"\236\001\n" +
      "\020SearchResultItem\022\016\n\006msg_id\030\001 \001(\004\022\022\n\nses" +
      "sion_id\030\002 \001(\004\022\016\n\006seq_id\030\003 \001(\004\022\021\n\tsender_" +
      "id\030\004 \001(\004\022\026\n\016create_time_ms\030\005 \001(\003\022\031\n\021high" +
      "light_content\030\006 \001(\t\022\020\n\010msg_type\030\007 \001(\0052}\n" +
      "\024StorageSearchService\022e\n\016SearchMessages\022" +
      "(.com.plato.gateway.SearchMessagesReques" +
      "t\032).com.plato.gateway.SearchMessagesResp" +
      "onseB<\n\020com.plato.searchP\001Z&github.com/p" +
      "lato/proto/gateway;gatewayb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_plato_gateway_SearchMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_plato_gateway_SearchMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SearchMessagesRequest_descriptor,
        new java.lang.String[] { "Keyword", "SessionId", "OwnerId", "MsgTypes", "StartTimeMs", "EndTimeMs", "SenderIds", "PageNumber", "PageSize", "Scope", });
    internal_static_com_plato_gateway_SearchMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_plato_gateway_SearchMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SearchMessagesResponse_descriptor,
        new java.lang.String[] { "Items", "TotalHits", });
    internal_static_com_plato_gateway_SearchResultItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_plato_gateway_SearchResultItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SearchResultItem_descriptor,
        new java.lang.String[] { "MsgId", "SessionId", "SeqId", "SenderId", "CreateTimeMs", "HighlightContent", "MsgType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
