// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
