// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

/**
 * Protobuf type {@code com.plato.gateway.GetInboxesResponse}
 */
public final class GetInboxesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.gateway.GetInboxesResponse)
    GetInboxesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetInboxesResponse.newBuilder() to construct.
  private GetInboxesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetInboxesResponse() {
    inboxes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetInboxesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_GetInboxesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_GetInboxesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.gateway.GetInboxesResponse.class, com.plato.gateway.GetInboxesResponse.Builder.class);
  }

  public static final int INBOXES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.plato.gateway.InboxItem> inboxes_;
  /**
   * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.plato.gateway.InboxItem> getInboxesList() {
    return inboxes_;
  }
  /**
   * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.plato.gateway.InboxItemOrBuilder> 
      getInboxesOrBuilderList() {
    return inboxes_;
  }
  /**
   * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
   */
  @java.lang.Override
  public int getInboxesCount() {
    return inboxes_.size();
  }
  /**
   * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
   */
  @java.lang.Override
  public com.plato.gateway.InboxItem getInboxes(int index) {
    return inboxes_.get(index);
  }
  /**
   * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
   */
  @java.lang.Override
  public com.plato.gateway.InboxItemOrBuilder getInboxesOrBuilder(
      int index) {
    return inboxes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < inboxes_.size(); i++) {
      output.writeMessage(1, inboxes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < inboxes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, inboxes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.gateway.GetInboxesResponse)) {
      return super.equals(obj);
    }
    com.plato.gateway.GetInboxesResponse other = (com.plato.gateway.GetInboxesResponse) obj;

    if (!getInboxesList()
        .equals(other.getInboxesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInboxesCount() > 0) {
      hash = (37 * hash) + INBOXES_FIELD_NUMBER;
      hash = (53 * hash) + getInboxesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.gateway.GetInboxesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.gateway.GetInboxesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.gateway.GetInboxesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.GetInboxesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.gateway.GetInboxesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.gateway.GetInboxesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.gateway.GetInboxesResponse)
      com.plato.gateway.GetInboxesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_GetInboxesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_GetInboxesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.gateway.GetInboxesResponse.class, com.plato.gateway.GetInboxesResponse.Builder.class);
    }

    // Construct using com.plato.gateway.GetInboxesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (inboxesBuilder_ == null) {
        inboxes_ = java.util.Collections.emptyList();
      } else {
        inboxes_ = null;
        inboxesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_GetInboxesResponse_descriptor;
    }

    @java.lang.Override
    public com.plato.gateway.GetInboxesResponse getDefaultInstanceForType() {
      return com.plato.gateway.GetInboxesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.gateway.GetInboxesResponse build() {
      com.plato.gateway.GetInboxesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.gateway.GetInboxesResponse buildPartial() {
      com.plato.gateway.GetInboxesResponse result = new com.plato.gateway.GetInboxesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.plato.gateway.GetInboxesResponse result) {
      if (inboxesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          inboxes_ = java.util.Collections.unmodifiableList(inboxes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.inboxes_ = inboxes_;
      } else {
        result.inboxes_ = inboxesBuilder_.build();
      }
    }

    private void buildPartial0(com.plato.gateway.GetInboxesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.gateway.GetInboxesResponse) {
        return mergeFrom((com.plato.gateway.GetInboxesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.gateway.GetInboxesResponse other) {
      if (other == com.plato.gateway.GetInboxesResponse.getDefaultInstance()) return this;
      if (inboxesBuilder_ == null) {
        if (!other.inboxes_.isEmpty()) {
          if (inboxes_.isEmpty()) {
            inboxes_ = other.inboxes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInboxesIsMutable();
            inboxes_.addAll(other.inboxes_);
          }
          onChanged();
        }
      } else {
        if (!other.inboxes_.isEmpty()) {
          if (inboxesBuilder_.isEmpty()) {
            inboxesBuilder_.dispose();
            inboxesBuilder_ = null;
            inboxes_ = other.inboxes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            inboxesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInboxesFieldBuilder() : null;
          } else {
            inboxesBuilder_.addAllMessages(other.inboxes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.plato.gateway.InboxItem m =
                  input.readMessage(
                      com.plato.gateway.InboxItem.parser(),
                      extensionRegistry);
              if (inboxesBuilder_ == null) {
                ensureInboxesIsMutable();
                inboxes_.add(m);
              } else {
                inboxesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.plato.gateway.InboxItem> inboxes_ =
      java.util.Collections.emptyList();
    private void ensureInboxesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        inboxes_ = new java.util.ArrayList<com.plato.gateway.InboxItem>(inboxes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plato.gateway.InboxItem, com.plato.gateway.InboxItem.Builder, com.plato.gateway.InboxItemOrBuilder> inboxesBuilder_;

    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public java.util.List<com.plato.gateway.InboxItem> getInboxesList() {
      if (inboxesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(inboxes_);
      } else {
        return inboxesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public int getInboxesCount() {
      if (inboxesBuilder_ == null) {
        return inboxes_.size();
      } else {
        return inboxesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public com.plato.gateway.InboxItem getInboxes(int index) {
      if (inboxesBuilder_ == null) {
        return inboxes_.get(index);
      } else {
        return inboxesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder setInboxes(
        int index, com.plato.gateway.InboxItem value) {
      if (inboxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInboxesIsMutable();
        inboxes_.set(index, value);
        onChanged();
      } else {
        inboxesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder setInboxes(
        int index, com.plato.gateway.InboxItem.Builder builderForValue) {
      if (inboxesBuilder_ == null) {
        ensureInboxesIsMutable();
        inboxes_.set(index, builderForValue.build());
        onChanged();
      } else {
        inboxesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder addInboxes(com.plato.gateway.InboxItem value) {
      if (inboxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInboxesIsMutable();
        inboxes_.add(value);
        onChanged();
      } else {
        inboxesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder addInboxes(
        int index, com.plato.gateway.InboxItem value) {
      if (inboxesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInboxesIsMutable();
        inboxes_.add(index, value);
        onChanged();
      } else {
        inboxesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder addInboxes(
        com.plato.gateway.InboxItem.Builder builderForValue) {
      if (inboxesBuilder_ == null) {
        ensureInboxesIsMutable();
        inboxes_.add(builderForValue.build());
        onChanged();
      } else {
        inboxesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder addInboxes(
        int index, com.plato.gateway.InboxItem.Builder builderForValue) {
      if (inboxesBuilder_ == null) {
        ensureInboxesIsMutable();
        inboxes_.add(index, builderForValue.build());
        onChanged();
      } else {
        inboxesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder addAllInboxes(
        java.lang.Iterable<? extends com.plato.gateway.InboxItem> values) {
      if (inboxesBuilder_ == null) {
        ensureInboxesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inboxes_);
        onChanged();
      } else {
        inboxesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder clearInboxes() {
      if (inboxesBuilder_ == null) {
        inboxes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        inboxesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public Builder removeInboxes(int index) {
      if (inboxesBuilder_ == null) {
        ensureInboxesIsMutable();
        inboxes_.remove(index);
        onChanged();
      } else {
        inboxesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public com.plato.gateway.InboxItem.Builder getInboxesBuilder(
        int index) {
      return getInboxesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public com.plato.gateway.InboxItemOrBuilder getInboxesOrBuilder(
        int index) {
      if (inboxesBuilder_ == null) {
        return inboxes_.get(index);  } else {
        return inboxesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public java.util.List<? extends com.plato.gateway.InboxItemOrBuilder> 
         getInboxesOrBuilderList() {
      if (inboxesBuilder_ != null) {
        return inboxesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(inboxes_);
      }
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public com.plato.gateway.InboxItem.Builder addInboxesBuilder() {
      return getInboxesFieldBuilder().addBuilder(
          com.plato.gateway.InboxItem.getDefaultInstance());
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public com.plato.gateway.InboxItem.Builder addInboxesBuilder(
        int index) {
      return getInboxesFieldBuilder().addBuilder(
          index, com.plato.gateway.InboxItem.getDefaultInstance());
    }
    /**
     * <code>repeated .com.plato.gateway.InboxItem inboxes = 1;</code>
     */
    public java.util.List<com.plato.gateway.InboxItem.Builder> 
         getInboxesBuilderList() {
      return getInboxesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plato.gateway.InboxItem, com.plato.gateway.InboxItem.Builder, com.plato.gateway.InboxItemOrBuilder> 
        getInboxesFieldBuilder() {
      if (inboxesBuilder_ == null) {
        inboxesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.plato.gateway.InboxItem, com.plato.gateway.InboxItem.Builder, com.plato.gateway.InboxItemOrBuilder>(
                inboxes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        inboxes_ = null;
      }
      return inboxesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.gateway.GetInboxesResponse)
  }

  // @@protoc_insertion_point(class_scope:com.plato.gateway.GetInboxesResponse)
  private static final com.plato.gateway.GetInboxesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.gateway.GetInboxesResponse();
  }

  public static com.plato.gateway.GetInboxesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetInboxesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetInboxesResponse>() {
    @java.lang.Override
    public GetInboxesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetInboxesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetInboxesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.gateway.GetInboxesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

