// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public interface GetMessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.GetMessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.plato.gateway.Message messages = 1;</code>
   */
  java.util.List<com.plato.gateway.Message> 
      getMessagesList();
  /**
   * <code>repeated .com.plato.gateway.Message messages = 1;</code>
   */
  com.plato.gateway.Message getMessages(int index);
  /**
   * <code>repeated .com.plato.gateway.Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .com.plato.gateway.Message messages = 1;</code>
   */
  java.util.List<? extends com.plato.gateway.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .com.plato.gateway.Message messages = 1;</code>
   */
  com.plato.gateway.MessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <pre>
   * 是否还有更多
   * </pre>
   *
   * <code>bool has_more = 2;</code>
   * @return The hasMore.
   */
  boolean getHasMore();
}
