// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public interface GetMessagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.GetMessagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 session_id = 1;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <pre>
   * 锚点 SeqID。0 表示最新/最旧
   * </pre>
   *
   * <code>uint64 anchor_seq_id = 2;</code>
   * @return The anchorSeqId.
   */
  long getAnchorSeqId();

  /**
   * <code>.com.plato.gateway.GetMessagesRequest.Direction direction = 3;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.com.plato.gateway.GetMessagesRequest.Direction direction = 3;</code>
   * @return The direction.
   */
  com.plato.gateway.GetMessagesRequest.Direction getDirection();

  /**
   * <pre>
   * 限制条数，e.g. 50
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   * @return The limit.
   */
  int getLimit();
}
