// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

/**
 * Protobuf type {@code com.plato.gateway.SaveMessageResult}
 */
public final class SaveMessageResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.gateway.SaveMessageResult)
    SaveMessageResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SaveMessageResult.newBuilder() to construct.
  private SaveMessageResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SaveMessageResult() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SaveMessageResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessageResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessageResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.gateway.SaveMessageResult.class, com.plato.gateway.SaveMessageResult.Builder.class);
  }

  private int resultCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SUCCESS(1),
    ERROR(2),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return ERROR;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  /**
   * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
   * @return Whether the success field is set.
   */
  @java.lang.Override
  public boolean hasSuccess() {
    return resultCase_ == 1;
  }
  /**
   * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public com.plato.gateway.SaveMessageResponse getSuccess() {
    if (resultCase_ == 1) {
       return (com.plato.gateway.SaveMessageResponse) result_;
    }
    return com.plato.gateway.SaveMessageResponse.getDefaultInstance();
  }
  /**
   * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
   */
  @java.lang.Override
  public com.plato.gateway.SaveMessageResponseOrBuilder getSuccessOrBuilder() {
    if (resultCase_ == 1) {
       return (com.plato.gateway.SaveMessageResponse) result_;
    }
    return com.plato.gateway.SaveMessageResponse.getDefaultInstance();
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  /**
   * <pre>
   * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
   * </pre>
   *
   * <code>.com.plato.gateway.Error error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return resultCase_ == 2;
  }
  /**
   * <pre>
   * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
   * </pre>
   *
   * <code>.com.plato.gateway.Error error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.plato.gateway.Error getError() {
    if (resultCase_ == 2) {
       return (com.plato.gateway.Error) result_;
    }
    return com.plato.gateway.Error.getDefaultInstance();
  }
  /**
   * <pre>
   * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
   * </pre>
   *
   * <code>.com.plato.gateway.Error error = 2;</code>
   */
  @java.lang.Override
  public com.plato.gateway.ErrorOrBuilder getErrorOrBuilder() {
    if (resultCase_ == 2) {
       return (com.plato.gateway.Error) result_;
    }
    return com.plato.gateway.Error.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resultCase_ == 1) {
      output.writeMessage(1, (com.plato.gateway.SaveMessageResponse) result_);
    }
    if (resultCase_ == 2) {
      output.writeMessage(2, (com.plato.gateway.Error) result_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resultCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.plato.gateway.SaveMessageResponse) result_);
    }
    if (resultCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.plato.gateway.Error) result_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.gateway.SaveMessageResult)) {
      return super.equals(obj);
    }
    com.plato.gateway.SaveMessageResult other = (com.plato.gateway.SaveMessageResult) obj;

    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 1:
        if (!getSuccess()
            .equals(other.getSuccess())) return false;
        break;
      case 2:
        if (!getError()
            .equals(other.getError())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resultCase_) {
      case 1:
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + getSuccess().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.gateway.SaveMessageResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.gateway.SaveMessageResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.gateway.SaveMessageResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.SaveMessageResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.gateway.SaveMessageResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.gateway.SaveMessageResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.gateway.SaveMessageResult)
      com.plato.gateway.SaveMessageResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessageResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessageResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.gateway.SaveMessageResult.class, com.plato.gateway.SaveMessageResult.Builder.class);
    }

    // Construct using com.plato.gateway.SaveMessageResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (successBuilder_ != null) {
        successBuilder_.clear();
      }
      if (errorBuilder_ != null) {
        errorBuilder_.clear();
      }
      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessageResult_descriptor;
    }

    @java.lang.Override
    public com.plato.gateway.SaveMessageResult getDefaultInstanceForType() {
      return com.plato.gateway.SaveMessageResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.gateway.SaveMessageResult build() {
      com.plato.gateway.SaveMessageResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.gateway.SaveMessageResult buildPartial() {
      com.plato.gateway.SaveMessageResult result = new com.plato.gateway.SaveMessageResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.plato.gateway.SaveMessageResult result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.plato.gateway.SaveMessageResult result) {
      result.resultCase_ = resultCase_;
      result.result_ = this.result_;
      if (resultCase_ == 1 &&
          successBuilder_ != null) {
        result.result_ = successBuilder_.build();
      }
      if (resultCase_ == 2 &&
          errorBuilder_ != null) {
        result.result_ = errorBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.gateway.SaveMessageResult) {
        return mergeFrom((com.plato.gateway.SaveMessageResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.gateway.SaveMessageResult other) {
      if (other == com.plato.gateway.SaveMessageResult.getDefaultInstance()) return this;
      switch (other.getResultCase()) {
        case SUCCESS: {
          mergeSuccess(other.getSuccess());
          break;
        }
        case ERROR: {
          mergeError(other.getError());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSuccessFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              resultCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.plato.gateway.SaveMessageResponse, com.plato.gateway.SaveMessageResponse.Builder, com.plato.gateway.SaveMessageResponseOrBuilder> successBuilder_;
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     * @return Whether the success field is set.
     */
    @java.lang.Override
    public boolean hasSuccess() {
      return resultCase_ == 1;
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public com.plato.gateway.SaveMessageResponse getSuccess() {
      if (successBuilder_ == null) {
        if (resultCase_ == 1) {
          return (com.plato.gateway.SaveMessageResponse) result_;
        }
        return com.plato.gateway.SaveMessageResponse.getDefaultInstance();
      } else {
        if (resultCase_ == 1) {
          return successBuilder_.getMessage();
        }
        return com.plato.gateway.SaveMessageResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    public Builder setSuccess(com.plato.gateway.SaveMessageResponse value) {
      if (successBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        successBuilder_.setMessage(value);
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    public Builder setSuccess(
        com.plato.gateway.SaveMessageResponse.Builder builderForValue) {
      if (successBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        successBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    public Builder mergeSuccess(com.plato.gateway.SaveMessageResponse value) {
      if (successBuilder_ == null) {
        if (resultCase_ == 1 &&
            result_ != com.plato.gateway.SaveMessageResponse.getDefaultInstance()) {
          result_ = com.plato.gateway.SaveMessageResponse.newBuilder((com.plato.gateway.SaveMessageResponse) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 1) {
          successBuilder_.mergeFrom(value);
        } else {
          successBuilder_.setMessage(value);
        }
      }
      resultCase_ = 1;
      return this;
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    public Builder clearSuccess() {
      if (successBuilder_ == null) {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 1) {
          resultCase_ = 0;
          result_ = null;
        }
        successBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    public com.plato.gateway.SaveMessageResponse.Builder getSuccessBuilder() {
      return getSuccessFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    @java.lang.Override
    public com.plato.gateway.SaveMessageResponseOrBuilder getSuccessOrBuilder() {
      if ((resultCase_ == 1) && (successBuilder_ != null)) {
        return successBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 1) {
          return (com.plato.gateway.SaveMessageResponse) result_;
        }
        return com.plato.gateway.SaveMessageResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.com.plato.gateway.SaveMessageResponse success = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.plato.gateway.SaveMessageResponse, com.plato.gateway.SaveMessageResponse.Builder, com.plato.gateway.SaveMessageResponseOrBuilder> 
        getSuccessFieldBuilder() {
      if (successBuilder_ == null) {
        if (!(resultCase_ == 1)) {
          result_ = com.plato.gateway.SaveMessageResponse.getDefaultInstance();
        }
        successBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.plato.gateway.SaveMessageResponse, com.plato.gateway.SaveMessageResponse.Builder, com.plato.gateway.SaveMessageResponseOrBuilder>(
                (com.plato.gateway.SaveMessageResponse) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 1;
      onChanged();
      return successBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.plato.gateway.Error, com.plato.gateway.Error.Builder, com.plato.gateway.ErrorOrBuilder> errorBuilder_;
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return resultCase_ == 2;
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     * @return The error.
     */
    @java.lang.Override
    public com.plato.gateway.Error getError() {
      if (errorBuilder_ == null) {
        if (resultCase_ == 2) {
          return (com.plato.gateway.Error) result_;
        }
        return com.plato.gateway.Error.getDefaultInstance();
      } else {
        if (resultCase_ == 2) {
          return errorBuilder_.getMessage();
        }
        return com.plato.gateway.Error.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    public Builder setError(com.plato.gateway.Error value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    public Builder setError(
        com.plato.gateway.Error.Builder builderForValue) {
      if (errorBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    public Builder mergeError(com.plato.gateway.Error value) {
      if (errorBuilder_ == null) {
        if (resultCase_ == 2 &&
            result_ != com.plato.gateway.Error.getDefaultInstance()) {
          result_ = com.plato.gateway.Error.newBuilder((com.plato.gateway.Error) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 2) {
          errorBuilder_.mergeFrom(value);
        } else {
          errorBuilder_.setMessage(value);
        }
      }
      resultCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
        }
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    public com.plato.gateway.Error.Builder getErrorBuilder() {
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    @java.lang.Override
    public com.plato.gateway.ErrorOrBuilder getErrorOrBuilder() {
      if ((resultCase_ == 2) && (errorBuilder_ != null)) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 2) {
          return (com.plato.gateway.Error) result_;
        }
        return com.plato.gateway.Error.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 局部失败 (e.g. 甚至不需要，因为一般要么全成要么全败，但为了健壮性可留)
     * </pre>
     *
     * <code>.com.plato.gateway.Error error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.plato.gateway.Error, com.plato.gateway.Error.Builder, com.plato.gateway.ErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        if (!(resultCase_ == 2)) {
          result_ = com.plato.gateway.Error.getDefaultInstance();
        }
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.plato.gateway.Error, com.plato.gateway.Error.Builder, com.plato.gateway.ErrorOrBuilder>(
                (com.plato.gateway.Error) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 2;
      onChanged();
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.gateway.SaveMessageResult)
  }

  // @@protoc_insertion_point(class_scope:com.plato.gateway.SaveMessageResult)
  private static final com.plato.gateway.SaveMessageResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.gateway.SaveMessageResult();
  }

  public static com.plato.gateway.SaveMessageResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SaveMessageResult>
      PARSER = new com.google.protobuf.AbstractParser<SaveMessageResult>() {
    @java.lang.Override
    public SaveMessageResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SaveMessageResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SaveMessageResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.gateway.SaveMessageResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

