// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

/**
 * Protobuf type {@code com.plato.gateway.SaveMessagesResponse}
 */
public final class SaveMessagesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.gateway.SaveMessagesResponse)
    SaveMessagesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SaveMessagesResponse.newBuilder() to construct.
  private SaveMessagesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SaveMessagesResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SaveMessagesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessagesResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetResults();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessagesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.gateway.SaveMessagesResponse.class, com.plato.gateway.SaveMessagesResponse.Builder.class);
  }

  public static final int RESULTS_FIELD_NUMBER = 1;
  private static final class ResultsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.plato.gateway.SaveMessageResult> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.plato.gateway.SaveMessageResult>newDefaultInstance(
                com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessagesResponse_ResultsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.plato.gateway.SaveMessageResult.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.plato.gateway.SaveMessageResult> results_;
  private com.google.protobuf.MapField<java.lang.String, com.plato.gateway.SaveMessageResult>
  internalGetResults() {
    if (results_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ResultsDefaultEntryHolder.defaultEntry);
    }
    return results_;
  }
  public int getResultsCount() {
    return internalGetResults().getMap().size();
  }
  /**
   * <pre>
   * Key: client_message_id (用于回填对应关系)
   * Value: 结果
   * </pre>
   *
   * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
   */
  @java.lang.Override
  public boolean containsResults(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetResults().getMap().containsKey(key);
  }
  /**
   * Use {@link #getResultsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> getResults() {
    return getResultsMap();
  }
  /**
   * <pre>
   * Key: client_message_id (用于回填对应关系)
   * Value: 结果
   * </pre>
   *
   * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> getResultsMap() {
    return internalGetResults().getMap();
  }
  /**
   * <pre>
   * Key: client_message_id (用于回填对应关系)
   * Value: 结果
   * </pre>
   *
   * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
com.plato.gateway.SaveMessageResult getResultsOrDefault(
      java.lang.String key,
      /* nullable */
com.plato.gateway.SaveMessageResult defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> map =
        internalGetResults().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Key: client_message_id (用于回填对应关系)
   * Value: 结果
   * </pre>
   *
   * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
   */
  @java.lang.Override
  public com.plato.gateway.SaveMessageResult getResultsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> map =
        internalGetResults().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetResults(),
        ResultsDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.plato.gateway.SaveMessageResult> entry
         : internalGetResults().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.plato.gateway.SaveMessageResult>
      results__ = ResultsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.gateway.SaveMessagesResponse)) {
      return super.equals(obj);
    }
    com.plato.gateway.SaveMessagesResponse other = (com.plato.gateway.SaveMessagesResponse) obj;

    if (!internalGetResults().equals(
        other.internalGetResults())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetResults().getMap().isEmpty()) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetResults().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.gateway.SaveMessagesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.gateway.SaveMessagesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.SaveMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.gateway.SaveMessagesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.gateway.SaveMessagesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.gateway.SaveMessagesResponse)
      com.plato.gateway.SaveMessagesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessagesResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableResults();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessagesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.gateway.SaveMessagesResponse.class, com.plato.gateway.SaveMessagesResponse.Builder.class);
    }

    // Construct using com.plato.gateway.SaveMessagesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableResults().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SaveMessagesResponse_descriptor;
    }

    @java.lang.Override
    public com.plato.gateway.SaveMessagesResponse getDefaultInstanceForType() {
      return com.plato.gateway.SaveMessagesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.gateway.SaveMessagesResponse build() {
      com.plato.gateway.SaveMessagesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.gateway.SaveMessagesResponse buildPartial() {
      com.plato.gateway.SaveMessagesResponse result = new com.plato.gateway.SaveMessagesResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.plato.gateway.SaveMessagesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.results_ = internalGetResults().build(ResultsDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.gateway.SaveMessagesResponse) {
        return mergeFrom((com.plato.gateway.SaveMessagesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.gateway.SaveMessagesResponse other) {
      if (other == com.plato.gateway.SaveMessagesResponse.getDefaultInstance()) return this;
      internalGetMutableResults().mergeFrom(
          other.internalGetResults());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.plato.gateway.SaveMessageResult>
              results__ = input.readMessage(
                  ResultsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableResults().ensureBuilderMap().put(
                  results__.getKey(), results__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ResultsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder, com.plato.gateway.SaveMessageResult> {
      @java.lang.Override
      public com.plato.gateway.SaveMessageResult build(com.plato.gateway.SaveMessageResultOrBuilder val) {
        if (val instanceof com.plato.gateway.SaveMessageResult) { return (com.plato.gateway.SaveMessageResult) val; }
        return ((com.plato.gateway.SaveMessageResult.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.plato.gateway.SaveMessageResult> defaultEntry() {
        return ResultsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ResultsConverter resultsConverter = new ResultsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder, com.plato.gateway.SaveMessageResult, com.plato.gateway.SaveMessageResult.Builder> results_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder, com.plato.gateway.SaveMessageResult, com.plato.gateway.SaveMessageResult.Builder>
        internalGetResults() {
      if (results_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(resultsConverter);
      }
      return results_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder, com.plato.gateway.SaveMessageResult, com.plato.gateway.SaveMessageResult.Builder>
        internalGetMutableResults() {
      if (results_ == null) {
        results_ = new com.google.protobuf.MapFieldBuilder<>(resultsConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return results_;
    }
    public int getResultsCount() {
      return internalGetResults().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    @java.lang.Override
    public boolean containsResults(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetResults().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getResultsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> getResults() {
      return getResultsMap();
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> getResultsMap() {
      return internalGetResults().getImmutableMap();
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.plato.gateway.SaveMessageResult getResultsOrDefault(
        java.lang.String key,
        /* nullable */
com.plato.gateway.SaveMessageResult defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder> map = internalGetMutableResults().ensureBuilderMap();
      return map.containsKey(key) ? resultsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    @java.lang.Override
    public com.plato.gateway.SaveMessageResult getResultsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder> map = internalGetMutableResults().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return resultsConverter.build(map.get(key));
    }
    public Builder clearResults() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableResults().clear();
      return this;
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    public Builder removeResults(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableResults().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult>
        getMutableResults() {
      bitField0_ |= 0x00000001;
      return internalGetMutableResults().ensureMessageMap();
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    public Builder putResults(
        java.lang.String key,
        com.plato.gateway.SaveMessageResult value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableResults().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    public Builder putAllResults(
        java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResult> values) {
      for (java.util.Map.Entry<java.lang.String, com.plato.gateway.SaveMessageResult> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableResults().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * Key: client_message_id (用于回填对应关系)
     * Value: 结果
     * </pre>
     *
     * <code>map&lt;string, .com.plato.gateway.SaveMessageResult&gt; results = 1;</code>
     */
    public com.plato.gateway.SaveMessageResult.Builder putResultsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.plato.gateway.SaveMessageResultOrBuilder> builderMap = internalGetMutableResults().ensureBuilderMap();
      com.plato.gateway.SaveMessageResultOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.plato.gateway.SaveMessageResult.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.plato.gateway.SaveMessageResult) {
        entry = ((com.plato.gateway.SaveMessageResult) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.plato.gateway.SaveMessageResult.Builder) entry;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.gateway.SaveMessagesResponse)
  }

  // @@protoc_insertion_point(class_scope:com.plato.gateway.SaveMessagesResponse)
  private static final com.plato.gateway.SaveMessagesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.gateway.SaveMessagesResponse();
  }

  public static com.plato.gateway.SaveMessagesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SaveMessagesResponse>
      PARSER = new com.google.protobuf.AbstractParser<SaveMessagesResponse>() {
    @java.lang.Override
    public SaveMessagesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SaveMessagesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SaveMessagesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.gateway.SaveMessagesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

