// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

/**
 * Protobuf type {@code com.plato.gateway.SetInboxAttributesRequest}
 */
public final class SetInboxAttributesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.gateway.SetInboxAttributesRequest)
    SetInboxAttributesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetInboxAttributesRequest.newBuilder() to construct.
  private SetInboxAttributesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetInboxAttributesRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetInboxAttributesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SetInboxAttributesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SetInboxAttributesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.gateway.SetInboxAttributesRequest.class, com.plato.gateway.SetInboxAttributesRequest.Builder.class);
  }

  private int attributeCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object attribute_;
  public enum AttributeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    IS_PINNED(3),
    IS_MUTED(4),
    ATTRIBUTE_NOT_SET(0);
    private final int value;
    private AttributeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AttributeCase valueOf(int value) {
      return forNumber(value);
    }

    public static AttributeCase forNumber(int value) {
      switch (value) {
        case 3: return IS_PINNED;
        case 4: return IS_MUTED;
        case 0: return ATTRIBUTE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AttributeCase
  getAttributeCase() {
    return AttributeCase.forNumber(
        attributeCase_);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <code>uint64 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 2;
  private long sessionId_ = 0L;
  /**
   * <code>uint64 session_id = 2;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public long getSessionId() {
    return sessionId_;
  }

  public static final int IS_PINNED_FIELD_NUMBER = 3;
  /**
   * <code>bool is_pinned = 3;</code>
   * @return Whether the isPinned field is set.
   */
  @java.lang.Override
  public boolean hasIsPinned() {
    return attributeCase_ == 3;
  }
  /**
   * <code>bool is_pinned = 3;</code>
   * @return The isPinned.
   */
  @java.lang.Override
  public boolean getIsPinned() {
    if (attributeCase_ == 3) {
      return (java.lang.Boolean) attribute_;
    }
    return false;
  }

  public static final int IS_MUTED_FIELD_NUMBER = 4;
  /**
   * <code>bool is_muted = 4;</code>
   * @return Whether the isMuted field is set.
   */
  @java.lang.Override
  public boolean hasIsMuted() {
    return attributeCase_ == 4;
  }
  /**
   * <code>bool is_muted = 4;</code>
   * @return The isMuted.
   */
  @java.lang.Override
  public boolean getIsMuted() {
    if (attributeCase_ == 4) {
      return (java.lang.Boolean) attribute_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeUInt64(1, userId_);
    }
    if (sessionId_ != 0L) {
      output.writeUInt64(2, sessionId_);
    }
    if (attributeCase_ == 3) {
      output.writeBool(
          3, (boolean)((java.lang.Boolean) attribute_));
    }
    if (attributeCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) attribute_));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, userId_);
    }
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, sessionId_);
    }
    if (attributeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            3, (boolean)((java.lang.Boolean) attribute_));
    }
    if (attributeCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) attribute_));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.gateway.SetInboxAttributesRequest)) {
      return super.equals(obj);
    }
    com.plato.gateway.SetInboxAttributesRequest other = (com.plato.gateway.SetInboxAttributesRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getSessionId()
        != other.getSessionId()) return false;
    if (!getAttributeCase().equals(other.getAttributeCase())) return false;
    switch (attributeCase_) {
      case 3:
        if (getIsPinned()
            != other.getIsPinned()) return false;
        break;
      case 4:
        if (getIsMuted()
            != other.getIsMuted()) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    switch (attributeCase_) {
      case 3:
        hash = (37 * hash) + IS_PINNED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsPinned());
        break;
      case 4:
        hash = (37 * hash) + IS_MUTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsMuted());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.gateway.SetInboxAttributesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.gateway.SetInboxAttributesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.SetInboxAttributesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.gateway.SetInboxAttributesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.gateway.SetInboxAttributesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.gateway.SetInboxAttributesRequest)
      com.plato.gateway.SetInboxAttributesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SetInboxAttributesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SetInboxAttributesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.gateway.SetInboxAttributesRequest.class, com.plato.gateway.SetInboxAttributesRequest.Builder.class);
    }

    // Construct using com.plato.gateway.SetInboxAttributesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      sessionId_ = 0L;
      attributeCase_ = 0;
      attribute_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_SetInboxAttributesRequest_descriptor;
    }

    @java.lang.Override
    public com.plato.gateway.SetInboxAttributesRequest getDefaultInstanceForType() {
      return com.plato.gateway.SetInboxAttributesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.gateway.SetInboxAttributesRequest build() {
      com.plato.gateway.SetInboxAttributesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.gateway.SetInboxAttributesRequest buildPartial() {
      com.plato.gateway.SetInboxAttributesRequest result = new com.plato.gateway.SetInboxAttributesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.plato.gateway.SetInboxAttributesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sessionId_ = sessionId_;
      }
    }

    private void buildPartialOneofs(com.plato.gateway.SetInboxAttributesRequest result) {
      result.attributeCase_ = attributeCase_;
      result.attribute_ = this.attribute_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.gateway.SetInboxAttributesRequest) {
        return mergeFrom((com.plato.gateway.SetInboxAttributesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.gateway.SetInboxAttributesRequest other) {
      if (other == com.plato.gateway.SetInboxAttributesRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      switch (other.getAttributeCase()) {
        case IS_PINNED: {
          setIsPinned(other.getIsPinned());
          break;
        }
        case IS_MUTED: {
          setIsMuted(other.getIsMuted());
          break;
        }
        case ATTRIBUTE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              sessionId_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              attribute_ = input.readBool();
              attributeCase_ = 3;
              break;
            } // case 24
            case 32: {
              attribute_ = input.readBool();
              attributeCase_ = 4;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int attributeCase_ = 0;
    private java.lang.Object attribute_;
    public AttributeCase
        getAttributeCase() {
      return AttributeCase.forNumber(
          attributeCase_);
    }

    public Builder clearAttribute() {
      attributeCase_ = 0;
      attribute_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private long userId_ ;
    /**
     * <code>uint64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>uint64 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long sessionId_ ;
    /**
     * <code>uint64 session_id = 2;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <code>uint64 session_id = 2;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(long value) {

      sessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 session_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>bool is_pinned = 3;</code>
     * @return Whether the isPinned field is set.
     */
    public boolean hasIsPinned() {
      return attributeCase_ == 3;
    }
    /**
     * <code>bool is_pinned = 3;</code>
     * @return The isPinned.
     */
    public boolean getIsPinned() {
      if (attributeCase_ == 3) {
        return (java.lang.Boolean) attribute_;
      }
      return false;
    }
    /**
     * <code>bool is_pinned = 3;</code>
     * @param value The isPinned to set.
     * @return This builder for chaining.
     */
    public Builder setIsPinned(boolean value) {

      attributeCase_ = 3;
      attribute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_pinned = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPinned() {
      if (attributeCase_ == 3) {
        attributeCase_ = 0;
        attribute_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool is_muted = 4;</code>
     * @return Whether the isMuted field is set.
     */
    public boolean hasIsMuted() {
      return attributeCase_ == 4;
    }
    /**
     * <code>bool is_muted = 4;</code>
     * @return The isMuted.
     */
    public boolean getIsMuted() {
      if (attributeCase_ == 4) {
        return (java.lang.Boolean) attribute_;
      }
      return false;
    }
    /**
     * <code>bool is_muted = 4;</code>
     * @param value The isMuted to set.
     * @return This builder for chaining.
     */
    public Builder setIsMuted(boolean value) {

      attributeCase_ = 4;
      attribute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_muted = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsMuted() {
      if (attributeCase_ == 4) {
        attributeCase_ = 0;
        attribute_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.gateway.SetInboxAttributesRequest)
  }

  // @@protoc_insertion_point(class_scope:com.plato.gateway.SetInboxAttributesRequest)
  private static final com.plato.gateway.SetInboxAttributesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.gateway.SetInboxAttributesRequest();
  }

  public static com.plato.gateway.SetInboxAttributesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetInboxAttributesRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetInboxAttributesRequest>() {
    @java.lang.Override
    public SetInboxAttributesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SetInboxAttributesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetInboxAttributesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.gateway.SetInboxAttributesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

