// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public interface SetInboxReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.SetInboxReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>uint64 session_id = 2;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <pre>
   * 读到了哪里
   * </pre>
   *
   * <code>uint64 read_seq_id = 3;</code>
   * @return The readSeqId.
   */
  long getReadSeqId();
}
