// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public interface SetInboxAttributesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.SetInboxAttributesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>uint64 session_id = 2;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <code>bool is_pinned = 3;</code>
   * @return Whether the isPinned field is set.
   */
  boolean hasIsPinned();
  /**
   * <code>bool is_pinned = 3;</code>
   * @return The isPinned.
   */
  boolean getIsPinned();

  /**
   * <code>bool is_muted = 4;</code>
   * @return Whether the isMuted field is set.
   */
  boolean hasIsMuted();
  /**
   * <code>bool is_muted = 4;</code>
   * @return The isMuted.
   */
  boolean getIsMuted();

  com.plato.gateway.SetInboxAttributesRequest.AttributeCase getAttributeCase();
}
