// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public final class StorageGateway {
  private StorageGateway() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessageRequest_ExtraEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessageRequest_ExtraEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessagesResponse_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessagesResponse_ResultsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SaveMessageResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SaveMessageResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_GetMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_GetMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_GetMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_GetMessagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_Message_ExtraEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_Message_ExtraEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_UpdateMessageStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_UpdateMessageStatusRequest_ExtensionEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_UpdateMessageStatusRequest_ExtensionEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_GetInboxesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_GetInboxesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_GetInboxesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_GetInboxesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_InboxItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_InboxItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SetInboxReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SetInboxReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_SetInboxAttributesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_SetInboxAttributesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_UpsertGroupMembersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_UpsertGroupMembersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_plato_gateway_RemoveGroupMembersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_plato_gateway_RemoveGroupMembersRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025storage_gateway.proto\022\021com.plato.gatew" +
      "ay\032\037google/protobuf/timestamp.proto\032\033goo" +
      "gle/protobuf/empty.proto\"\350\001\n\022SaveMessage" +
      "Request\022\022\n\nsession_id\030\001 \001(\004\022\021\n\tsender_id" +
      "\030\002 \001(\004\022\031\n\021client_message_id\030\003 \001(\t\022\020\n\010msg" +
      "_type\030\004 \001(\005\022\017\n\007content\030\005 \001(\014\022?\n\005extra\030\006 " +
      "\003(\01320.com.plato.gateway.SaveMessageReque" +
      "st.ExtraEntry\032,\n\nExtraEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\"M\n\023SaveMessageRespon" +
      "se\022\016\n\006msg_id\030\001 \001(\004\022\016\n\006seq_id\030\002 \001(\004\022\026\n\016se" +
      "rver_time_ms\030\003 \001(\003\"N\n\023SaveMessagesReques" +
      "t\0227\n\010requests\030\001 \003(\0132%.com.plato.gateway." +
      "SaveMessageRequest\"\263\001\n\024SaveMessagesRespo" +
      "nse\022E\n\007results\030\001 \003(\01324.com.plato.gateway" +
      ".SaveMessagesResponse.ResultsEntry\032T\n\014Re" +
      "sultsEntry\022\013\n\003key\030\001 \001(\t\0223\n\005value\030\002 \001(\0132$" +
      ".com.plato.gateway.SaveMessageResult:\0028\001" +
      "\"\203\001\n\021SaveMessageResult\0229\n\007success\030\001 \001(\0132" +
      "&.com.plato.gateway.SaveMessageResponseH" +
      "\000\022)\n\005error\030\002 \001(\0132\030.com.plato.gateway.Err" +
      "orH\000B\010\n\006result\"&\n\005Error\022\014\n\004code\030\001 \001(\005\022\017\n" +
      "\007message\030\002 \001(\t\"\272\001\n\022GetMessagesRequest\022\022\n" +
      "\nsession_id\030\001 \001(\004\022\025\n\ranchor_seq_id\030\002 \001(\004" +
      "\022B\n\tdirection\030\003 \001(\0162/.com.plato.gateway." +
      "GetMessagesRequest.Direction\022\r\n\005limit\030\004 " +
      "\001(\005\"&\n\tDirection\022\014\n\010BACKWARD\020\000\022\013\n\007FORWAR" +
      "D\020\001\"U\n\023GetMessagesResponse\022,\n\010messages\030\001" +
      " \003(\0132\032.com.plato.gateway.Message\022\020\n\010has_" +
      "more\030\002 \001(\010\"\377\001\n\007Message\022\016\n\006msg_id\030\001 \001(\004\022\022" +
      "\n\nsession_id\030\002 \001(\004\022\016\n\006seq_id\030\003 \001(\004\022\021\n\tse" +
      "nder_id\030\004 \001(\004\022\020\n\010msg_type\030\005 \001(\005\022\017\n\007conte" +
      "nt\030\006 \001(\014\022\016\n\006status\030\007 \001(\005\022\026\n\016create_time_" +
      "ms\030\010 \001(\003\0224\n\005extra\030\t \003(\0132%.com.plato.gate" +
      "way.Message.ExtraEntry\032,\n\nExtraEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\327\001\n\032UpdateM" +
      "essageStatusRequest\022\022\n\nsession_id\030\001 \001(\004\022" +
      "\016\n\006seq_id\030\002 \001(\004\022\022\n\nnew_status\030\003 \001(\005\022O\n\te" +
      "xtension\030\004 \003(\0132<.com.plato.gateway.Updat" +
      "eMessageStatusRequest.ExtensionEntry\0320\n\016" +
      "ExtensionEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\"K\n\021GetInboxesRequest\022\017\n\007user_id\030\001" +
      " \001(\004\022\026\n\016anchor_time_ms\030\002 \001(\003\022\r\n\005limit\030\003 " +
      "\001(\005\"C\n\022GetInboxesResponse\022-\n\007inboxes\030\001 \003" +
      "(\0132\034.com.plato.gateway.InboxItem\"\262\001\n\tInb" +
      "oxItem\022\022\n\nsession_id\030\001 \001(\004\022\024\n\014unread_cou" +
      "nt\030\002 \001(\005\022 \n\030last_msg_content_preview\030\003 \001" +
      "(\t\022\030\n\020last_msg_time_ms\030\004 \001(\003\022\032\n\022last_msg" +
      "_sender_id\030\005 \001(\004\022\021\n\tis_pinned\030\006 \001(\010\022\020\n\010i" +
      "s_muted\030\007 \001(\010\"O\n\023SetInboxReadRequest\022\017\n\007" +
      "user_id\030\001 \001(\004\022\022\n\nsession_id\030\002 \001(\004\022\023\n\013rea" +
      "d_seq_id\030\003 \001(\004\"v\n\031SetInboxAttributesRequ" +
      "est\022\017\n\007user_id\030\001 \001(\004\022\022\n\nsession_id\030\002 \001(\004" +
      "\022\023\n\tis_pinned\030\003 \001(\010H\000\022\022\n\010is_muted\030\004 \001(\010H" +
      "\000B\013\n\tattribute\"C\n\031UpsertGroupMembersRequ" +
      "est\022\022\n\nsession_id\030\001 \001(\004\022\022\n\nmember_ids\030\002 " +
      "\003(\004\"C\n\031RemoveGroupMembersRequest\022\022\n\nsess" +
      "ion_id\030\001 \001(\004\022\022\n\nmember_ids\030\002 \003(\0042\222\003\n\025Sto" +
      "rageMessageService\022\\\n\013SaveMessage\022%.com." +
      "plato.gateway.SaveMessageRequest\032&.com.p" +
      "lato.gateway.SaveMessageResponse\022_\n\014Save" +
      "Messages\022&.com.plato.gateway.SaveMessage" +
      "sRequest\032\'.com.plato.gateway.SaveMessage" +
      "sResponse\022\\\n\013GetMessages\022%.com.plato.gat" +
      "eway.GetMessagesRequest\032&.com.plato.gate" +
      "way.GetMessagesResponse\022\\\n\023UpdateMessage" +
      "Status\022-.com.plato.gateway.UpdateMessage" +
      "StatusRequest\032\026.google.protobuf.Empty2\234\002" +
      "\n\023StorageInboxService\022Y\n\nGetInboxes\022$.co" +
      "m.plato.gateway.GetInboxesRequest\032%.com." +
      "plato.gateway.GetInboxesResponse\022N\n\014SetI" +
      "nboxRead\022&.com.plato.gateway.SetInboxRea" +
      "dRequest\032\026.google.protobuf.Empty\022Z\n\022SetI" +
      "nboxAttributes\022,.com.plato.gateway.SetIn" +
      "boxAttributesRequest\032\026.google.protobuf.E" +
      "mpty2\315\001\n\023StorageGroupService\022Z\n\022UpsertGr" +
      "oupMembers\022,.com.plato.gateway.UpsertGro" +
      "upMembersRequest\032\026.google.protobuf.Empty" +
      "\022Z\n\022RemoveGroupMembers\022,.com.plato.gatew" +
      "ay.RemoveGroupMembersRequest\032\026.google.pr" +
      "otobuf.EmptyB=\n\021com.plato.gatewayP\001Z&git" +
      "hub.com/plato/proto/gateway;gatewayb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_com_plato_gateway_SaveMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_plato_gateway_SaveMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessageRequest_descriptor,
        new java.lang.String[] { "SessionId", "SenderId", "ClientMessageId", "MsgType", "Content", "Extra", });
    internal_static_com_plato_gateway_SaveMessageRequest_ExtraEntry_descriptor =
      internal_static_com_plato_gateway_SaveMessageRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_plato_gateway_SaveMessageRequest_ExtraEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessageRequest_ExtraEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_plato_gateway_SaveMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_plato_gateway_SaveMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessageResponse_descriptor,
        new java.lang.String[] { "MsgId", "SeqId", "ServerTimeMs", });
    internal_static_com_plato_gateway_SaveMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_plato_gateway_SaveMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessagesRequest_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_com_plato_gateway_SaveMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_plato_gateway_SaveMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessagesResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_com_plato_gateway_SaveMessagesResponse_ResultsEntry_descriptor =
      internal_static_com_plato_gateway_SaveMessagesResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_plato_gateway_SaveMessagesResponse_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessagesResponse_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_plato_gateway_SaveMessageResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_plato_gateway_SaveMessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SaveMessageResult_descriptor,
        new java.lang.String[] { "Success", "Error", "Result", });
    internal_static_com_plato_gateway_Error_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_plato_gateway_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_Error_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_com_plato_gateway_GetMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_plato_gateway_GetMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_GetMessagesRequest_descriptor,
        new java.lang.String[] { "SessionId", "AnchorSeqId", "Direction", "Limit", });
    internal_static_com_plato_gateway_GetMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_plato_gateway_GetMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_GetMessagesResponse_descriptor,
        new java.lang.String[] { "Messages", "HasMore", });
    internal_static_com_plato_gateway_Message_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_plato_gateway_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_Message_descriptor,
        new java.lang.String[] { "MsgId", "SessionId", "SeqId", "SenderId", "MsgType", "Content", "Status", "CreateTimeMs", "Extra", });
    internal_static_com_plato_gateway_Message_ExtraEntry_descriptor =
      internal_static_com_plato_gateway_Message_descriptor.getNestedTypes().get(0);
    internal_static_com_plato_gateway_Message_ExtraEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_Message_ExtraEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_plato_gateway_UpdateMessageStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor,
        new java.lang.String[] { "SessionId", "SeqId", "NewStatus", "Extension", });
    internal_static_com_plato_gateway_UpdateMessageStatusRequest_ExtensionEntry_descriptor =
      internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_plato_gateway_UpdateMessageStatusRequest_ExtensionEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_UpdateMessageStatusRequest_ExtensionEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_plato_gateway_GetInboxesRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_plato_gateway_GetInboxesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_GetInboxesRequest_descriptor,
        new java.lang.String[] { "UserId", "AnchorTimeMs", "Limit", });
    internal_static_com_plato_gateway_GetInboxesResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_plato_gateway_GetInboxesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_GetInboxesResponse_descriptor,
        new java.lang.String[] { "Inboxes", });
    internal_static_com_plato_gateway_InboxItem_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_plato_gateway_InboxItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_InboxItem_descriptor,
        new java.lang.String[] { "SessionId", "UnreadCount", "LastMsgContentPreview", "LastMsgTimeMs", "LastMsgSenderId", "IsPinned", "IsMuted", });
    internal_static_com_plato_gateway_SetInboxReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_plato_gateway_SetInboxReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SetInboxReadRequest_descriptor,
        new java.lang.String[] { "UserId", "SessionId", "ReadSeqId", });
    internal_static_com_plato_gateway_SetInboxAttributesRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_plato_gateway_SetInboxAttributesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_SetInboxAttributesRequest_descriptor,
        new java.lang.String[] { "UserId", "SessionId", "IsPinned", "IsMuted", "Attribute", });
    internal_static_com_plato_gateway_UpsertGroupMembersRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_plato_gateway_UpsertGroupMembersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_UpsertGroupMembersRequest_descriptor,
        new java.lang.String[] { "SessionId", "MemberIds", });
    internal_static_com_plato_gateway_RemoveGroupMembersRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_plato_gateway_RemoveGroupMembersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_plato_gateway_RemoveGroupMembersRequest_descriptor,
        new java.lang.String[] { "SessionId", "MemberIds", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
