// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

/**
 * Protobuf type {@code com.plato.gateway.UpdateMessageStatusRequest}
 */
public final class UpdateMessageStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.gateway.UpdateMessageStatusRequest)
    UpdateMessageStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateMessageStatusRequest.newBuilder() to construct.
  private UpdateMessageStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateMessageStatusRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateMessageStatusRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 4:
        return internalGetExtension();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_UpdateMessageStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.gateway.UpdateMessageStatusRequest.class, com.plato.gateway.UpdateMessageStatusRequest.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private long sessionId_ = 0L;
  /**
   * <code>uint64 session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public long getSessionId() {
    return sessionId_;
  }

  public static final int SEQ_ID_FIELD_NUMBER = 2;
  private long seqId_ = 0L;
  /**
   * <pre>
   * 只需要 SeqID 就能定位 (配合 SessionID)
   * </pre>
   *
   * <code>uint64 seq_id = 2;</code>
   * @return The seqId.
   */
  @java.lang.Override
  public long getSeqId() {
    return seqId_;
  }

  public static final int NEW_STATUS_FIELD_NUMBER = 3;
  private int newStatus_ = 0;
  /**
   * <pre>
   * e.g., 1=RECALLED
   * </pre>
   *
   * <code>int32 new_status = 3;</code>
   * @return The newStatus.
   */
  @java.lang.Override
  public int getNewStatus() {
    return newStatus_;
  }

  public static final int EXTENSION_FIELD_NUMBER = 4;
  private static final class ExtensionDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_UpdateMessageStatusRequest_ExtensionEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> extension_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExtension() {
    if (extension_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtensionDefaultEntryHolder.defaultEntry);
    }
    return extension_;
  }
  public int getExtensionCount() {
    return internalGetExtension().getMap().size();
  }
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  @java.lang.Override
  public boolean containsExtension(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetExtension().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtensionMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExtension() {
    return getExtensionMap();
  }
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getExtensionMap() {
    return internalGetExtension().getMap();
  }
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getExtensionOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtension().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getExtensionOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtension().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sessionId_ != 0L) {
      output.writeUInt64(1, sessionId_);
    }
    if (seqId_ != 0L) {
      output.writeUInt64(2, seqId_);
    }
    if (newStatus_ != 0) {
      output.writeInt32(3, newStatus_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetExtension(),
        ExtensionDefaultEntryHolder.defaultEntry,
        4);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sessionId_);
    }
    if (seqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, seqId_);
    }
    if (newStatus_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, newStatus_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExtension().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      extension__ = ExtensionDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, extension__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.gateway.UpdateMessageStatusRequest)) {
      return super.equals(obj);
    }
    com.plato.gateway.UpdateMessageStatusRequest other = (com.plato.gateway.UpdateMessageStatusRequest) obj;

    if (getSessionId()
        != other.getSessionId()) return false;
    if (getSeqId()
        != other.getSeqId()) return false;
    if (getNewStatus()
        != other.getNewStatus()) return false;
    if (!internalGetExtension().equals(
        other.internalGetExtension())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    hash = (37 * hash) + SEQ_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeqId());
    hash = (37 * hash) + NEW_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getNewStatus();
    if (!internalGetExtension().getMap().isEmpty()) {
      hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtension().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.gateway.UpdateMessageStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.gateway.UpdateMessageStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.gateway.UpdateMessageStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.gateway.UpdateMessageStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.gateway.UpdateMessageStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.gateway.UpdateMessageStatusRequest)
      com.plato.gateway.UpdateMessageStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetExtension();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableExtension();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_UpdateMessageStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.gateway.UpdateMessageStatusRequest.class, com.plato.gateway.UpdateMessageStatusRequest.Builder.class);
    }

    // Construct using com.plato.gateway.UpdateMessageStatusRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = 0L;
      seqId_ = 0L;
      newStatus_ = 0;
      internalGetMutableExtension().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.gateway.StorageGateway.internal_static_com_plato_gateway_UpdateMessageStatusRequest_descriptor;
    }

    @java.lang.Override
    public com.plato.gateway.UpdateMessageStatusRequest getDefaultInstanceForType() {
      return com.plato.gateway.UpdateMessageStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.gateway.UpdateMessageStatusRequest build() {
      com.plato.gateway.UpdateMessageStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.gateway.UpdateMessageStatusRequest buildPartial() {
      com.plato.gateway.UpdateMessageStatusRequest result = new com.plato.gateway.UpdateMessageStatusRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.plato.gateway.UpdateMessageStatusRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.seqId_ = seqId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.newStatus_ = newStatus_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.extension_ = internalGetExtension();
        result.extension_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.gateway.UpdateMessageStatusRequest) {
        return mergeFrom((com.plato.gateway.UpdateMessageStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.gateway.UpdateMessageStatusRequest other) {
      if (other == com.plato.gateway.UpdateMessageStatusRequest.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (other.getSeqId() != 0L) {
        setSeqId(other.getSeqId());
      }
      if (other.getNewStatus() != 0) {
        setNewStatus(other.getNewStatus());
      }
      internalGetMutableExtension().mergeFrom(
          other.internalGetExtension());
      bitField0_ |= 0x00000008;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sessionId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              seqId_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              newStatus_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extension__ = input.readMessage(
                  ExtensionDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableExtension().getMutableMap().put(
                  extension__.getKey(), extension__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long sessionId_ ;
    /**
     * <code>uint64 session_id = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <code>uint64 session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(long value) {

      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private long seqId_ ;
    /**
     * <pre>
     * 只需要 SeqID 就能定位 (配合 SessionID)
     * </pre>
     *
     * <code>uint64 seq_id = 2;</code>
     * @return The seqId.
     */
    @java.lang.Override
    public long getSeqId() {
      return seqId_;
    }
    /**
     * <pre>
     * 只需要 SeqID 就能定位 (配合 SessionID)
     * </pre>
     *
     * <code>uint64 seq_id = 2;</code>
     * @param value The seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqId(long value) {

      seqId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 只需要 SeqID 就能定位 (配合 SessionID)
     * </pre>
     *
     * <code>uint64 seq_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      seqId_ = 0L;
      onChanged();
      return this;
    }

    private int newStatus_ ;
    /**
     * <pre>
     * e.g., 1=RECALLED
     * </pre>
     *
     * <code>int32 new_status = 3;</code>
     * @return The newStatus.
     */
    @java.lang.Override
    public int getNewStatus() {
      return newStatus_;
    }
    /**
     * <pre>
     * e.g., 1=RECALLED
     * </pre>
     *
     * <code>int32 new_status = 3;</code>
     * @param value The newStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNewStatus(int value) {

      newStatus_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., 1=RECALLED
     * </pre>
     *
     * <code>int32 new_status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      newStatus_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extension_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetExtension() {
      if (extension_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtensionDefaultEntryHolder.defaultEntry);
      }
      return extension_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableExtension() {
      if (extension_ == null) {
        extension_ = com.google.protobuf.MapField.newMapField(
            ExtensionDefaultEntryHolder.defaultEntry);
      }
      if (!extension_.isMutable()) {
        extension_ = extension_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return extension_;
    }
    public int getExtensionCount() {
      return internalGetExtension().getMap().size();
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    @java.lang.Override
    public boolean containsExtension(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExtension().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtensionMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtension() {
      return getExtensionMap();
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getExtensionMap() {
      return internalGetExtension().getMap();
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getExtensionOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtension().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getExtensionOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtension().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearExtension() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableExtension().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    public Builder removeExtension(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableExtension().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableExtension() {
      bitField0_ |= 0x00000008;
      return internalGetMutableExtension().getMutableMap();
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    public Builder putExtension(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableExtension().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <pre>
     * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
     * </pre>
     *
     * <code>map&lt;string, string&gt; extension = 4;</code>
     */
    public Builder putAllExtension(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExtension().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.gateway.UpdateMessageStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:com.plato.gateway.UpdateMessageStatusRequest)
  private static final com.plato.gateway.UpdateMessageStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.gateway.UpdateMessageStatusRequest();
  }

  public static com.plato.gateway.UpdateMessageStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateMessageStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateMessageStatusRequest>() {
    @java.lang.Override
    public UpdateMessageStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateMessageStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateMessageStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.gateway.UpdateMessageStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

