// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_gateway.proto

// Protobuf Java Version: 3.25.5
package com.plato.gateway;

public interface UpdateMessageStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.gateway.UpdateMessageStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 session_id = 1;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <pre>
   * 只需要 SeqID 就能定位 (配合 SessionID)
   * </pre>
   *
   * <code>uint64 seq_id = 2;</code>
   * @return The seqId.
   */
  long getSeqId();

  /**
   * <pre>
   * e.g., 1=RECALLED
   * </pre>
   *
   * <code>int32 new_status = 3;</code>
   * @return The newStatus.
   */
  int getNewStatus();

  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  int getExtensionCount();
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  boolean containsExtension(
      java.lang.String key);
  /**
   * Use {@link #getExtensionMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtension();
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtensionMap();
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  /* nullable */
java.lang.String getExtensionOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * e.g., 存撤回者的ID，或者"管理员删除了此消息"的提示文案
   * </pre>
   *
   * <code>map&lt;string, string&gt; extension = 4;</code>
   */
  java.lang.String getExtensionOrThrow(
      java.lang.String key);
}
