// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_admin.proto

// Protobuf Java Version: 3.25.5
package com.plato.admin;

/**
 * Protobuf type {@code com.plato.storage.admin.v1.PatchGroupMembersRequest}
 */
public final class PatchGroupMembersRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.storage.admin.v1.PatchGroupMembersRequest)
    PatchGroupMembersRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PatchGroupMembersRequest.newBuilder() to construct.
  private PatchGroupMembersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PatchGroupMembersRequest() {
    addedMemberIds_ = emptyLongList();
    removedMemberIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PatchGroupMembersRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_PatchGroupMembersRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_PatchGroupMembersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.admin.PatchGroupMembersRequest.class, com.plato.admin.PatchGroupMembersRequest.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private long sessionId_ = 0L;
  /**
   * <code>uint64 session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public long getSessionId() {
    return sessionId_;
  }

  public static final int ADDED_MEMBER_IDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList addedMemberIds_ =
      emptyLongList();
  /**
   * <pre>
   * 要添加的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 added_member_ids = 2;</code>
   * @return A list containing the addedMemberIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getAddedMemberIdsList() {
    return addedMemberIds_;
  }
  /**
   * <pre>
   * 要添加的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 added_member_ids = 2;</code>
   * @return The count of addedMemberIds.
   */
  public int getAddedMemberIdsCount() {
    return addedMemberIds_.size();
  }
  /**
   * <pre>
   * 要添加的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 added_member_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The addedMemberIds at the given index.
   */
  public long getAddedMemberIds(int index) {
    return addedMemberIds_.getLong(index);
  }
  private int addedMemberIdsMemoizedSerializedSize = -1;

  public static final int REMOVED_MEMBER_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList removedMemberIds_ =
      emptyLongList();
  /**
   * <pre>
   * 要移除的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 removed_member_ids = 3;</code>
   * @return A list containing the removedMemberIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getRemovedMemberIdsList() {
    return removedMemberIds_;
  }
  /**
   * <pre>
   * 要移除的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 removed_member_ids = 3;</code>
   * @return The count of removedMemberIds.
   */
  public int getRemovedMemberIdsCount() {
    return removedMemberIds_.size();
  }
  /**
   * <pre>
   * 要移除的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 removed_member_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The removedMemberIds at the given index.
   */
  public long getRemovedMemberIds(int index) {
    return removedMemberIds_.getLong(index);
  }
  private int removedMemberIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (sessionId_ != 0L) {
      output.writeUInt64(1, sessionId_);
    }
    if (getAddedMemberIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(addedMemberIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < addedMemberIds_.size(); i++) {
      output.writeUInt64NoTag(addedMemberIds_.getLong(i));
    }
    if (getRemovedMemberIdsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(removedMemberIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < removedMemberIds_.size(); i++) {
      output.writeUInt64NoTag(removedMemberIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sessionId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < addedMemberIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(addedMemberIds_.getLong(i));
      }
      size += dataSize;
      if (!getAddedMemberIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      addedMemberIdsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < removedMemberIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(removedMemberIds_.getLong(i));
      }
      size += dataSize;
      if (!getRemovedMemberIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      removedMemberIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.admin.PatchGroupMembersRequest)) {
      return super.equals(obj);
    }
    com.plato.admin.PatchGroupMembersRequest other = (com.plato.admin.PatchGroupMembersRequest) obj;

    if (getSessionId()
        != other.getSessionId()) return false;
    if (!getAddedMemberIdsList()
        .equals(other.getAddedMemberIdsList())) return false;
    if (!getRemovedMemberIdsList()
        .equals(other.getRemovedMemberIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    if (getAddedMemberIdsCount() > 0) {
      hash = (37 * hash) + ADDED_MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getAddedMemberIdsList().hashCode();
    }
    if (getRemovedMemberIdsCount() > 0) {
      hash = (37 * hash) + REMOVED_MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getRemovedMemberIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.admin.PatchGroupMembersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.admin.PatchGroupMembersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.admin.PatchGroupMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.admin.PatchGroupMembersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.storage.admin.v1.PatchGroupMembersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.storage.admin.v1.PatchGroupMembersRequest)
      com.plato.admin.PatchGroupMembersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_PatchGroupMembersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_PatchGroupMembersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.admin.PatchGroupMembersRequest.class, com.plato.admin.PatchGroupMembersRequest.Builder.class);
    }

    // Construct using com.plato.admin.PatchGroupMembersRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = 0L;
      addedMemberIds_ = emptyLongList();
      removedMemberIds_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_PatchGroupMembersRequest_descriptor;
    }

    @java.lang.Override
    public com.plato.admin.PatchGroupMembersRequest getDefaultInstanceForType() {
      return com.plato.admin.PatchGroupMembersRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.admin.PatchGroupMembersRequest build() {
      com.plato.admin.PatchGroupMembersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.admin.PatchGroupMembersRequest buildPartial() {
      com.plato.admin.PatchGroupMembersRequest result = new com.plato.admin.PatchGroupMembersRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.plato.admin.PatchGroupMembersRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        addedMemberIds_.makeImmutable();
        result.addedMemberIds_ = addedMemberIds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        removedMemberIds_.makeImmutable();
        result.removedMemberIds_ = removedMemberIds_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.admin.PatchGroupMembersRequest) {
        return mergeFrom((com.plato.admin.PatchGroupMembersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.admin.PatchGroupMembersRequest other) {
      if (other == com.plato.admin.PatchGroupMembersRequest.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (!other.addedMemberIds_.isEmpty()) {
        if (addedMemberIds_.isEmpty()) {
          addedMemberIds_ = other.addedMemberIds_;
          addedMemberIds_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureAddedMemberIdsIsMutable();
          addedMemberIds_.addAll(other.addedMemberIds_);
        }
        onChanged();
      }
      if (!other.removedMemberIds_.isEmpty()) {
        if (removedMemberIds_.isEmpty()) {
          removedMemberIds_ = other.removedMemberIds_;
          removedMemberIds_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureRemovedMemberIdsIsMutable();
          removedMemberIds_.addAll(other.removedMemberIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sessionId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              long v = input.readUInt64();
              ensureAddedMemberIdsIsMutable();
              addedMemberIds_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureAddedMemberIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                addedMemberIds_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            case 24: {
              long v = input.readUInt64();
              ensureRemovedMemberIdsIsMutable();
              removedMemberIds_.addLong(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureRemovedMemberIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                removedMemberIds_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long sessionId_ ;
    /**
     * <code>uint64 session_id = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <code>uint64 session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(long value) {

      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList addedMemberIds_ = emptyLongList();
    private void ensureAddedMemberIdsIsMutable() {
      if (!addedMemberIds_.isModifiable()) {
        addedMemberIds_ = makeMutableCopy(addedMemberIds_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @return A list containing the addedMemberIds.
     */
    public java.util.List<java.lang.Long>
        getAddedMemberIdsList() {
      addedMemberIds_.makeImmutable();
      return addedMemberIds_;
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @return The count of addedMemberIds.
     */
    public int getAddedMemberIdsCount() {
      return addedMemberIds_.size();
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The addedMemberIds at the given index.
     */
    public long getAddedMemberIds(int index) {
      return addedMemberIds_.getLong(index);
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The addedMemberIds to set.
     * @return This builder for chaining.
     */
    public Builder setAddedMemberIds(
        int index, long value) {

      ensureAddedMemberIdsIsMutable();
      addedMemberIds_.setLong(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @param value The addedMemberIds to add.
     * @return This builder for chaining.
     */
    public Builder addAddedMemberIds(long value) {

      ensureAddedMemberIdsIsMutable();
      addedMemberIds_.addLong(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @param values The addedMemberIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllAddedMemberIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAddedMemberIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, addedMemberIds_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要添加的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 added_member_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddedMemberIds() {
      addedMemberIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList removedMemberIds_ = emptyLongList();
    private void ensureRemovedMemberIdsIsMutable() {
      if (!removedMemberIds_.isModifiable()) {
        removedMemberIds_ = makeMutableCopy(removedMemberIds_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @return A list containing the removedMemberIds.
     */
    public java.util.List<java.lang.Long>
        getRemovedMemberIdsList() {
      removedMemberIds_.makeImmutable();
      return removedMemberIds_;
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @return The count of removedMemberIds.
     */
    public int getRemovedMemberIdsCount() {
      return removedMemberIds_.size();
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The removedMemberIds at the given index.
     */
    public long getRemovedMemberIds(int index) {
      return removedMemberIds_.getLong(index);
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The removedMemberIds to set.
     * @return This builder for chaining.
     */
    public Builder setRemovedMemberIds(
        int index, long value) {

      ensureRemovedMemberIdsIsMutable();
      removedMemberIds_.setLong(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @param value The removedMemberIds to add.
     * @return This builder for chaining.
     */
    public Builder addRemovedMemberIds(long value) {

      ensureRemovedMemberIdsIsMutable();
      removedMemberIds_.addLong(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @param values The removedMemberIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllRemovedMemberIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureRemovedMemberIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, removedMemberIds_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 要移除的用户 ID 列表
     * </pre>
     *
     * <code>repeated uint64 removed_member_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemovedMemberIds() {
      removedMemberIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.storage.admin.v1.PatchGroupMembersRequest)
  }

  // @@protoc_insertion_point(class_scope:com.plato.storage.admin.v1.PatchGroupMembersRequest)
  private static final com.plato.admin.PatchGroupMembersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.admin.PatchGroupMembersRequest();
  }

  public static com.plato.admin.PatchGroupMembersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PatchGroupMembersRequest>
      PARSER = new com.google.protobuf.AbstractParser<PatchGroupMembersRequest>() {
    @java.lang.Override
    public PatchGroupMembersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PatchGroupMembersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PatchGroupMembersRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.admin.PatchGroupMembersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

