// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_admin.proto

// Protobuf Java Version: 3.25.5
package com.plato.admin;

public interface PatchGroupMembersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.plato.storage.admin.v1.PatchGroupMembersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 session_id = 1;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <pre>
   * 要添加的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 added_member_ids = 2;</code>
   * @return A list containing the addedMemberIds.
   */
  java.util.List<java.lang.Long> getAddedMemberIdsList();
  /**
   * <pre>
   * 要添加的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 added_member_ids = 2;</code>
   * @return The count of addedMemberIds.
   */
  int getAddedMemberIdsCount();
  /**
   * <pre>
   * 要添加的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 added_member_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The addedMemberIds at the given index.
   */
  long getAddedMemberIds(int index);

  /**
   * <pre>
   * 要移除的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 removed_member_ids = 3;</code>
   * @return A list containing the removedMemberIds.
   */
  java.util.List<java.lang.Long> getRemovedMemberIdsList();
  /**
   * <pre>
   * 要移除的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 removed_member_ids = 3;</code>
   * @return The count of removedMemberIds.
   */
  int getRemovedMemberIdsCount();
  /**
   * <pre>
   * 要移除的用户 ID 列表
   * </pre>
   *
   * <code>repeated uint64 removed_member_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The removedMemberIds at the given index.
   */
  long getRemovedMemberIds(int index);
}
