// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage_admin.proto

// Protobuf Java Version: 3.25.5
package com.plato.admin;

/**
 * Protobuf type {@code com.plato.storage.admin.v1.ResetGroupMembersRequest}
 */
public final class ResetGroupMembersRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.plato.storage.admin.v1.ResetGroupMembersRequest)
    ResetGroupMembersRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResetGroupMembersRequest.newBuilder() to construct.
  private ResetGroupMembersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResetGroupMembersRequest() {
    memberIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResetGroupMembersRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_ResetGroupMembersRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_ResetGroupMembersRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plato.admin.ResetGroupMembersRequest.class, com.plato.admin.ResetGroupMembersRequest.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private long sessionId_ = 0L;
  /**
   * <code>uint64 session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public long getSessionId() {
    return sessionId_;
  }

  public static final int MEMBER_IDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList memberIds_ =
      emptyLongList();
  /**
   * <pre>
   * 完整的成员 ID 列表
   * </pre>
   *
   * <code>repeated uint64 member_ids = 2;</code>
   * @return A list containing the memberIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getMemberIdsList() {
    return memberIds_;
  }
  /**
   * <pre>
   * 完整的成员 ID 列表
   * </pre>
   *
   * <code>repeated uint64 member_ids = 2;</code>
   * @return The count of memberIds.
   */
  public int getMemberIdsCount() {
    return memberIds_.size();
  }
  /**
   * <pre>
   * 完整的成员 ID 列表
   * </pre>
   *
   * <code>repeated uint64 member_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The memberIds at the given index.
   */
  public long getMemberIds(int index) {
    return memberIds_.getLong(index);
  }
  private int memberIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (sessionId_ != 0L) {
      output.writeUInt64(1, sessionId_);
    }
    if (getMemberIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(memberIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < memberIds_.size(); i++) {
      output.writeUInt64NoTag(memberIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, sessionId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < memberIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(memberIds_.getLong(i));
      }
      size += dataSize;
      if (!getMemberIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      memberIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plato.admin.ResetGroupMembersRequest)) {
      return super.equals(obj);
    }
    com.plato.admin.ResetGroupMembersRequest other = (com.plato.admin.ResetGroupMembersRequest) obj;

    if (getSessionId()
        != other.getSessionId()) return false;
    if (!getMemberIdsList()
        .equals(other.getMemberIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    if (getMemberIdsCount() > 0) {
      hash = (37 * hash) + MEMBER_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getMemberIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.plato.admin.ResetGroupMembersRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.plato.admin.ResetGroupMembersRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plato.admin.ResetGroupMembersRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plato.admin.ResetGroupMembersRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.plato.storage.admin.v1.ResetGroupMembersRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.plato.storage.admin.v1.ResetGroupMembersRequest)
      com.plato.admin.ResetGroupMembersRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_ResetGroupMembersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_ResetGroupMembersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.admin.ResetGroupMembersRequest.class, com.plato.admin.ResetGroupMembersRequest.Builder.class);
    }

    // Construct using com.plato.admin.ResetGroupMembersRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = 0L;
      memberIds_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plato.admin.StorageAdmin.internal_static_com_plato_storage_admin_v1_ResetGroupMembersRequest_descriptor;
    }

    @java.lang.Override
    public com.plato.admin.ResetGroupMembersRequest getDefaultInstanceForType() {
      return com.plato.admin.ResetGroupMembersRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.plato.admin.ResetGroupMembersRequest build() {
      com.plato.admin.ResetGroupMembersRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plato.admin.ResetGroupMembersRequest buildPartial() {
      com.plato.admin.ResetGroupMembersRequest result = new com.plato.admin.ResetGroupMembersRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.plato.admin.ResetGroupMembersRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        memberIds_.makeImmutable();
        result.memberIds_ = memberIds_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plato.admin.ResetGroupMembersRequest) {
        return mergeFrom((com.plato.admin.ResetGroupMembersRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plato.admin.ResetGroupMembersRequest other) {
      if (other == com.plato.admin.ResetGroupMembersRequest.getDefaultInstance()) return this;
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (!other.memberIds_.isEmpty()) {
        if (memberIds_.isEmpty()) {
          memberIds_ = other.memberIds_;
          memberIds_.makeImmutable();
          bitField0_ |= 0x00000002;
        } else {
          ensureMemberIdsIsMutable();
          memberIds_.addAll(other.memberIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sessionId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              long v = input.readUInt64();
              ensureMemberIdsIsMutable();
              memberIds_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureMemberIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                memberIds_.addLong(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long sessionId_ ;
    /**
     * <code>uint64 session_id = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <code>uint64 session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(long value) {

      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList memberIds_ = emptyLongList();
    private void ensureMemberIdsIsMutable() {
      if (!memberIds_.isModifiable()) {
        memberIds_ = makeMutableCopy(memberIds_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @return A list containing the memberIds.
     */
    public java.util.List<java.lang.Long>
        getMemberIdsList() {
      memberIds_.makeImmutable();
      return memberIds_;
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @return The count of memberIds.
     */
    public int getMemberIdsCount() {
      return memberIds_.size();
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The memberIds at the given index.
     */
    public long getMemberIds(int index) {
      return memberIds_.getLong(index);
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The memberIds to set.
     * @return This builder for chaining.
     */
    public Builder setMemberIds(
        int index, long value) {

      ensureMemberIdsIsMutable();
      memberIds_.setLong(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @param value The memberIds to add.
     * @return This builder for chaining.
     */
    public Builder addMemberIds(long value) {

      ensureMemberIdsIsMutable();
      memberIds_.addLong(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @param values The memberIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllMemberIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureMemberIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, memberIds_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完整的成员 ID 列表
     * </pre>
     *
     * <code>repeated uint64 member_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberIds() {
      memberIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.plato.storage.admin.v1.ResetGroupMembersRequest)
  }

  // @@protoc_insertion_point(class_scope:com.plato.storage.admin.v1.ResetGroupMembersRequest)
  private static final com.plato.admin.ResetGroupMembersRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plato.admin.ResetGroupMembersRequest();
  }

  public static com.plato.admin.ResetGroupMembersRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResetGroupMembersRequest>
      PARSER = new com.google.protobuf.AbstractParser<ResetGroupMembersRequest>() {
    @java.lang.Override
    public ResetGroupMembersRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResetGroupMembersRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResetGroupMembersRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plato.admin.ResetGroupMembersRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

