// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: id.proto

// Protobuf Java Version: 3.25.5
package com.plato.id.grpc;

public final class IdServiceProto {
  private IdServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenerateIdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:idservice.GenerateIdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 对应 0-63 的业务ID
     * </pre>
     *
     * <code>int32 bid = 1;</code>
     * @return The bid.
     */
    int getBid();
  }
  /**
   * <pre>
   * 请求消息：
   * 客户端需要传入 '业务ID' (bid)
   * </pre>
   *
   * Protobuf type {@code idservice.GenerateIdRequest}
   */
  public static final class GenerateIdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:idservice.GenerateIdRequest)
      GenerateIdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenerateIdRequest.newBuilder() to construct.
    private GenerateIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenerateIdRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenerateIdRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.id.grpc.IdServiceProto.GenerateIdRequest.class, com.plato.id.grpc.IdServiceProto.GenerateIdRequest.Builder.class);
    }

    public static final int BID_FIELD_NUMBER = 1;
    private int bid_ = 0;
    /**
     * <pre>
     * 对应 0-63 的业务ID
     * </pre>
     *
     * <code>int32 bid = 1;</code>
     * @return The bid.
     */
    @java.lang.Override
    public int getBid() {
      return bid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bid_ != 0) {
        output.writeInt32(1, bid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.plato.id.grpc.IdServiceProto.GenerateIdRequest)) {
        return super.equals(obj);
      }
      com.plato.id.grpc.IdServiceProto.GenerateIdRequest other = (com.plato.id.grpc.IdServiceProto.GenerateIdRequest) obj;

      if (getBid()
          != other.getBid()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BID_FIELD_NUMBER;
      hash = (53 * hash) + getBid();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.plato.id.grpc.IdServiceProto.GenerateIdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 请求消息：
     * 客户端需要传入 '业务ID' (bid)
     * </pre>
     *
     * Protobuf type {@code idservice.GenerateIdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:idservice.GenerateIdRequest)
        com.plato.id.grpc.IdServiceProto.GenerateIdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.plato.id.grpc.IdServiceProto.GenerateIdRequest.class, com.plato.id.grpc.IdServiceProto.GenerateIdRequest.Builder.class);
      }

      // Construct using com.plato.idservice.grpc.IdServiceProto.GenerateIdRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        bid_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdRequest_descriptor;
      }

      @java.lang.Override
      public com.plato.id.grpc.IdServiceProto.GenerateIdRequest getDefaultInstanceForType() {
        return com.plato.id.grpc.IdServiceProto.GenerateIdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.plato.id.grpc.IdServiceProto.GenerateIdRequest build() {
        com.plato.id.grpc.IdServiceProto.GenerateIdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.plato.id.grpc.IdServiceProto.GenerateIdRequest buildPartial() {
        com.plato.id.grpc.IdServiceProto.GenerateIdRequest result = new com.plato.id.grpc.IdServiceProto.GenerateIdRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.plato.id.grpc.IdServiceProto.GenerateIdRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.bid_ = bid_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.plato.id.grpc.IdServiceProto.GenerateIdRequest) {
          return mergeFrom((com.plato.id.grpc.IdServiceProto.GenerateIdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.plato.id.grpc.IdServiceProto.GenerateIdRequest other) {
        if (other == com.plato.id.grpc.IdServiceProto.GenerateIdRequest.getDefaultInstance()) return this;
        if (other.getBid() != 0) {
          setBid(other.getBid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bid_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <pre>
       * 对应 0-63 的业务ID
       * </pre>
       *
       * <code>int32 bid = 1;</code>
       * @return The bid.
       */
      @java.lang.Override
      public int getBid() {
        return bid_;
      }
      /**
       * <pre>
       * 对应 0-63 的业务ID
       * </pre>
       *
       * <code>int32 bid = 1;</code>
       * @param value The bid to set.
       * @return This builder for chaining.
       */
      public Builder setBid(int value) {

        bid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对应 0-63 的业务ID
       * </pre>
       *
       * <code>int32 bid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:idservice.GenerateIdRequest)
    }

    // @@protoc_insertion_point(class_scope:idservice.GenerateIdRequest)
    private static final com.plato.id.grpc.IdServiceProto.GenerateIdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.plato.id.grpc.IdServiceProto.GenerateIdRequest();
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenerateIdRequest>
        PARSER = new com.google.protobuf.AbstractParser<GenerateIdRequest>() {
      @java.lang.Override
      public GenerateIdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenerateIdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenerateIdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.plato.id.grpc.IdServiceProto.GenerateIdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenerateIdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:idservice.GenerateIdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * <pre>
   * 响应消息：
   * 服务端返回生成的 64位 ID
   * </pre>
   *
   * Protobuf type {@code idservice.GenerateIdResponse}
   */
  public static final class GenerateIdResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:idservice.GenerateIdResponse)
      GenerateIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenerateIdResponse.newBuilder() to construct.
    private GenerateIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenerateIdResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenerateIdResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plato.id.grpc.IdServiceProto.GenerateIdResponse.class, com.plato.id.grpc.IdServiceProto.GenerateIdResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.plato.id.grpc.IdServiceProto.GenerateIdResponse)) {
        return super.equals(obj);
      }
      com.plato.id.grpc.IdServiceProto.GenerateIdResponse other = (com.plato.id.grpc.IdServiceProto.GenerateIdResponse) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.plato.id.grpc.IdServiceProto.GenerateIdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应消息：
     * 服务端返回生成的 64位 ID
     * </pre>
     *
     * Protobuf type {@code idservice.GenerateIdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:idservice.GenerateIdResponse)
        com.plato.id.grpc.IdServiceProto.GenerateIdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.plato.id.grpc.IdServiceProto.GenerateIdResponse.class, com.plato.id.grpc.IdServiceProto.GenerateIdResponse.Builder.class);
      }

      // Construct using com.plato.idservice.grpc.IdServiceProto.GenerateIdResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.plato.id.grpc.IdServiceProto.internal_static_idservice_GenerateIdResponse_descriptor;
      }

      @java.lang.Override
      public com.plato.id.grpc.IdServiceProto.GenerateIdResponse getDefaultInstanceForType() {
        return com.plato.id.grpc.IdServiceProto.GenerateIdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.plato.id.grpc.IdServiceProto.GenerateIdResponse build() {
        com.plato.id.grpc.IdServiceProto.GenerateIdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.plato.id.grpc.IdServiceProto.GenerateIdResponse buildPartial() {
        com.plato.id.grpc.IdServiceProto.GenerateIdResponse result = new com.plato.id.grpc.IdServiceProto.GenerateIdResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.plato.id.grpc.IdServiceProto.GenerateIdResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.plato.id.grpc.IdServiceProto.GenerateIdResponse) {
          return mergeFrom((com.plato.id.grpc.IdServiceProto.GenerateIdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.plato.id.grpc.IdServiceProto.GenerateIdResponse other) {
        if (other == com.plato.id.grpc.IdServiceProto.GenerateIdResponse.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:idservice.GenerateIdResponse)
    }

    // @@protoc_insertion_point(class_scope:idservice.GenerateIdResponse)
    private static final com.plato.id.grpc.IdServiceProto.GenerateIdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.plato.id.grpc.IdServiceProto.GenerateIdResponse();
    }

    public static com.plato.id.grpc.IdServiceProto.GenerateIdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenerateIdResponse>
        PARSER = new com.google.protobuf.AbstractParser<GenerateIdResponse>() {
      @java.lang.Override
      public GenerateIdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenerateIdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenerateIdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.plato.id.grpc.IdServiceProto.GenerateIdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_idservice_GenerateIdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_idservice_GenerateIdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_idservice_GenerateIdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_idservice_GenerateIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010id.proto\022\tidservice\" \n\021GenerateIdReque" +
      "st\022\013\n\003bid\030\001 \001(\005\" \n\022GenerateIdResponse\022\n\n" +
      "\002id\030\001 \001(\0032X\n\tIdService\022K\n\nGenerateId\022\034.i" +
      "dservice.GenerateIdRequest\032\035.idservice.G" +
      "enerateIdResponse\"\000B*\n\030com.plato.idservi" +
      "ce.grpcB\016IdServiceProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_idservice_GenerateIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_idservice_GenerateIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_idservice_GenerateIdRequest_descriptor,
        new java.lang.String[] { "Bid", });
    internal_static_idservice_GenerateIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_idservice_GenerateIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_idservice_GenerateIdResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
